///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package clothesarchive;
//
//import clothesarchive.exceptions.CAException;
//import clothesarchive.services.CRUD.CrudServiceImpl;
//import clothesarchive.models.RecordDTO;
//import clothesarchive.services.*;
//import customFilters.CustomPictureFilter;
//import java.io.File;
//import java.io.FileReader;
//import java.io.IOException;
//import java.nio.file.Files;
//import java.sql.Timestamp;
//import java.util.HashSet;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JFileChooser;
//import javax.swing.JOptionPane;
//import clothesarchive.services.CRUD.CrudService;
//import static java.lang.Thread.sleep;
//
///**
// *
// * @author Valeri Dobrev
// */
//public class Screen extends javax.swing.JFrame {
//
//    private CrudService addService;
//    private byte[] file;
//
//    /**
//     * Creates new form Screen
//     */
//    public Screen() {
//        initComponents();
//        this.AddItem.setVisible(false);
//        this.EditItem.setVisible(false);
//        this.ListItems.setVisible(true);
//        try {
//            this.addService = new CrudServiceImpl();
//        } catch (CAException ex) {
//            ex.show(this.ListItems);
//            System.exit(0);
//        }
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//
//    private void initComponents() {
//
//        /**
//         * Action listener for button Add in Add Menu
//         */
//        private void btnAddActionPerformed (java.awt.event.ActionEvent evt){//GEN-FIRST:event_btnAddActionPerformed
//            try {
//                this.addService.saveRecord(this.nameField.getText(), this.descriptionField.getText(), this.companyField.getText(), Double.parseDouble(this.priceField.getText()), this.file);
//
//            } catch (CAException ex) {
//                System.out.println(ex.getStackTrace().toString());
//                ex.show(this.AddItem);
//                return;
//            }
//            this.clearAddFields();
//            this.updateList();
//            this.AddItem.setVisible(false);
//            this.ListItems.setVisible(true);
//        }//GEN-LAST:event_btnAddActionPerformed
//        /**
//         * Action listener for button Cancel in Add Menu
//         */
//        private void btnCancelActionPerformed (java.awt.event.ActionEvent evt)
//        {//GEN-FIRST:event_btnCancelActionPerformed
//            this.clearAddFields();
//            this.AddItem.setVisible(false);
//            this.ListItems.setVisible(true);
//        }//GEN-LAST:event_btnCancelActionPerformed
//        /**
//         * Listener for Choose file button in Add Menu
//         */
//        private void btnChooseFileActionPerformed (java.awt.event.ActionEvent evt)
//        {//GEN-FIRST:event_btnChooseFileActionPerformed
//            this.file = null;
//            int returnVal = fileChooser.showOpenDialog(this);
//            if (returnVal == JFileChooser.APPROVE_OPTION) {
//                File file = fileChooser.getSelectedFile();
//                this.pathField.setText(file.getAbsolutePath());
//
//                try {
//                    this.file = Files.readAllBytes(file.toPath());
//                } catch (IOException ex) {
//                    Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//            } else {
//                System.out.println("File access cancelled by user.");
//            }
//        }//GEN-LAST:event_btnChooseFileActionPerformed
//        /**
//         *  Event listener for clearing the priceField on focus
//         */
//        private void priceFieldOnFocus (java.awt.event.FocusEvent evt){//GEN-FIRST:event_priceFieldOnFocus
//            this.priceField.setText("");
//        }//GEN-LAST:event_priceFieldOnFocus
//
//        private void btnViewLMActionPerformed (java.awt.event.ActionEvent evt)
//        {//GEN-FIRST:event_btnViewLMActionPerformed
//            try {
//                if (this.recordsList.getSelectedValuesList().isEmpty()) {
//                    throw new CAException("Моля изберете запис!", 1);
//                }
//            } catch (CAException e) {
//                e.show(this.ListItems);
//            }
//        }
//
//        private void btnEditLMActionPerformed (java.awt.event.ActionEvent evt)
//        {//GEN-FIRST:event_btnEditLMActionPerformed
//            try {
//                if (this.recordsList.getSelectedValuesList().isEmpty()) {
//                    throw new CAException("Моля изберете запис!", 1);
//                }
//            } catch (CAException e) {
//                e.show(this.ListItems);
//            }
//        }//GEN-LAST:event_btnEditLMActionPerformed
//
//        private void btnAddLMActionPerformed (java.awt.event.ActionEvent evt){//GEN-FIRST:event_btnAddLMActionPerformed
//            this.ListItems.setVisible(false);
//            this.AddItem.setVisible(true);
//        }//GEN-LAST:event_btnAddLMActionPerformed
//
//        private void btnDeleteLMActionPerformed (java.awt.event.ActionEvent evt)
//        {//GEN-FIRST:event_btnDeleteLMActionPerformed
//            try {
//                if (this.recordsList.getSelectedValuesList().isEmpty()) {
//                    throw new CAException("Моля изберете запис!", 1);
//                }
//            } catch (CAException e) {
//                e.show(this.ListItems);
//            }
//        }
//    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new Screen().setVisible(true);
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel AddItem;
//    private javax.swing.JPanel EditItem;
//    private javax.swing.JPanel ListItems;
//    private javax.swing.JButton btnAdd;
//    private javax.swing.JButton btnAddLM;
//    private javax.swing.JButton btnCancel;
//    private javax.swing.JButton btnChooseFile;
//    private javax.swing.JButton btnDeleteLM;
//    private javax.swing.JButton btnEditLM;
//    private javax.swing.JButton btnViewLM;
//    private javax.swing.JTextField companyField;
//    private javax.swing.JTextField descriptionField;
//    private javax.swing.JFileChooser fileChooser;
//    private javax.swing.JLabel headline;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JLabel lCompany;
//    private javax.swing.JLabel lDescription;
//    private javax.swing.JLabel lName;
//    private javax.swing.JLabel lPrice;
//    private javax.swing.JTextField nameField;
//    private javax.swing.JTextField pathField;
//    private javax.swing.JFormattedTextField priceField;
//    private javax.swing.JList<String> recordsList;
//    // End of variables declaration//GEN-END:variables
//
//
//    /**
//     *    Method for updating the list in the home page after add/update
//    */
//    private void updateList() {
//
//    }
//
//    private void clearAddFields() {
//        this.nameField.setText("");
//        this.descriptionField.setText("");
//        this.companyField.setText("");
//        this.priceField.setText("");
//        this.pathField.setText("");
//    }
//}
