/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clothesarchive;

import clothesarchive.exceptions.CAException;
import clothesarchive.services.CRUD.CrudServiceImpl;
import clothesarchive.models.RecordDTO;
import clothesarchive.services.*;
import customFilters.CustomPictureFilter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import clothesarchive.services.CRUD.CrudService;
import static java.lang.Thread.sleep;

/**
 *
 * @author Valeri Dobrev
 */
public class Screen extends javax.swing.JFrame {

    private CrudService addService;
    private byte[] file;

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        this.AddItem.setVisible(false);
        this.EditItem.setVisible(false);
        this.ListItems.setVisible(true);
        try {
            this.addService = new CrudServiceImpl();
        } catch (CAException ex) {
            ex.show(this.ListItems);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        AddItem = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        lDescription = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        lCompany = new javax.swing.JLabel();
        companyField = new javax.swing.JTextField();
        lPrice = new javax.swing.JLabel();
        priceField = new javax.swing.JFormattedTextField();
        btnChooseFile = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pathField = new javax.swing.JTextField();
        EditItem = new javax.swing.JPanel();
        ListItems = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsList = new javax.swing.JList<>();
        btnAddLM = new javax.swing.JButton();
        btnViewLM = new javax.swing.JButton();
        btnEditLM = new javax.swing.JButton();
        btnDeleteLM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        fileChooser.setFileFilter(new CustomPictureFilter());
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        AddItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headline.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        headline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headline.setText("Добавяне на дреха");
        AddItem.add(headline, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 330, 60));

        lName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lName.setText("Наименование: ");
        AddItem.add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, 40));
        AddItem.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 250, 40));

        lDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDescription.setText("Описание: ");
        lDescription.setToolTipText("");
        AddItem.add(lDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, 40));
        AddItem.add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 250, 40));

        lCompany.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCompany.setText("Поръчител: ");
        lCompany.setToolTipText("");
        AddItem.add(lCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 110, 40));
        AddItem.add(companyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 250, 40));

        lPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPrice.setText("Цена:");
        AddItem.add(lPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 40));

        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        priceField.setText("0.00");
        priceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFieldOnFocus(evt);
            }
        });
        AddItem.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 50, 40));

        btnChooseFile.setText("Choose file...");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });
        AddItem.add(btnChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 110, 40));

        btnAdd.setText("Добави");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        AddItem.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 100, 30));

        btnCancel.setText("Откажи");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        AddItem.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 100, 30));

        pathField.setEnabled(false);
        AddItem.add(pathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 250, 40));

        getContentPane().add(AddItem, "card3");

        javax.swing.GroupLayout EditItemLayout = new javax.swing.GroupLayout(EditItem);
        EditItem.setLayout(EditItemLayout);
        EditItemLayout.setHorizontalGroup(
            EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        EditItemLayout.setVerticalGroup(
            EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(EditItem, "card4");

        ListItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordsList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        recordsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        recordsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        recordsList.setToolTipText("");
        jScrollPane1.setViewportView(recordsList);

        ListItems.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 560, 420));

        btnAddLM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddLM.setText("Добави");
        btnAddLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLMActionPerformed(evt);
            }
        });
        ListItems.add(btnAddLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 100, 30));

        btnViewLM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewLM.setText("Виж");
        btnViewLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLMActionPerformed(evt);
            }
        });
        ListItems.add(btnViewLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 110, 30));

        btnEditLM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditLM.setText("Редактирай");
        btnEditLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLMActionPerformed(evt);
            }
        });
        ListItems.add(btnEditLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 110, 30));

        btnDeleteLM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteLM.setText("Изтрий");
        btnDeleteLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLMActionPerformed(evt);
            }
        });
        ListItems.add(btnDeleteLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Списък с всички записи: ");
        ListItems.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 50));

        getContentPane().add(ListItems, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action listener for button Add in Add Menu
    */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            this.addService.saveRecord(this.nameField.getText(),this.descriptionField.getText(), this.companyField.getText(), Double.parseDouble(this.priceField.getText()), this.file);
            
        } catch (CAException ex) {
            System.out.println(ex.getStackTrace().toString());
            ex.show(this.AddItem);
            return;
        }
        this.clearAddFields();
        this.updateList();
        this.AddItem.setVisible(false);
        this.ListItems.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed
    /**
     * Action listener for button Cancel in Add Menu
    */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.clearAddFields();
        this.AddItem.setVisible(false);
        this.ListItems.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed
    /**
     * Listener for Choose file button in Add Menu
    */
    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        this.file = null;
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            this.pathField.setText(file.getAbsolutePath());

            try {
                this.file = Files.readAllBytes(file.toPath());
            } catch (IOException ex) {
                Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed
    /**
     *  Event listener for clearing the priceField on focus
    */
    private void priceFieldOnFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFieldOnFocus
        this.priceField.setText("");
    }//GEN-LAST:event_priceFieldOnFocus

    private void btnViewLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLMActionPerformed
        try{
            if(this.recordsList.getSelectedValuesList().isEmpty()){
                throw new CAException("Моля изберете запис!", 1);
            }
        }
        catch(CAException e){
                e.show(this.ListItems);
        }
    }//GEN-LAST:event_btnViewLMActionPerformed

    private void btnEditLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLMActionPerformed
        try{
            if(this.recordsList.getSelectedValuesList().isEmpty()){
                throw new CAException("Моля изберете запис!", 1);
            }
        }
        catch(CAException e){
                e.show(this.ListItems);
        }
    }//GEN-LAST:event_btnEditLMActionPerformed

    private void btnAddLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLMActionPerformed
        this.ListItems.setVisible(false);
        this.AddItem.setVisible(true);
    }//GEN-LAST:event_btnAddLMActionPerformed

    private void btnDeleteLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLMActionPerformed
        try{
            if(this.recordsList.getSelectedValuesList().isEmpty()){
                throw new CAException("Моля изберете запис!", 1);
            }
        }
        catch(CAException e){
                e.show(this.ListItems);
        }
    }//GEN-LAST:event_btnDeleteLMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddItem;
    private javax.swing.JPanel EditItem;
    private javax.swing.JPanel ListItems;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddLM;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnDeleteLM;
    private javax.swing.JButton btnEditLM;
    private javax.swing.JButton btnViewLM;
    private javax.swing.JTextField companyField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCompany;
    private javax.swing.JLabel lDescription;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lPrice;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField pathField;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JList<String> recordsList;
    // End of variables declaration//GEN-END:variables

   
    /**
     *    Method for updating the list in the home page after add/update
    */
    private void updateList() {

    }

    private void clearAddFields() {
        this.nameField.setText("");
        this.descriptionField.setText("");
        this.companyField.setText("");
        this.priceField.setText("");
        this.pathField.setText("");
    }
}
